/**
 * Allot
 * State management app
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { State } from './state';

 export interface Day {
    doctor?: State;
    homeOffice?: State;
    project?: State;
    holiday?: State;
}
