/**
 * Allot
 * State management app
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { Day } from './day';

/**
 * A map/dictionary structure in which the key is the day of the month, and the value are the states of that day
 */
 export interface Month { 
  [key: string]: Day;


}