/**
 * Allot
 * State management app
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { Project } from '../project';

 export interface User { 
    id: number;
    role: User.RoleEnum;
    name: string;
    surname: string;
    avatar?: string;
    projects: Array<Project>;
}
export namespace User {
    export type RoleEnum = 'USER' | 'ADMIN';
    export const RoleEnum = {
        USER: 'USER' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum
    };
}